# Generated by Django 5.0.7 on 2025-09-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
