# Generated by Django 5.0.7 on 2025-09-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_cover_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("einstein", "Einstein"),
                    ("shakespeare", "Shakespeare"),
                    ("davinci", "Leonardo da Vinci"),
                    ("mandela", "Nelson Mandela"),
                ],
                default="einstein",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["post", "type"], name="api_reactio_post_id_1e450b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["user", "post"], name="api_reactio_user_id_8cc9f7_idx"
            ),
        ),
    ]
