services:
  - type: web
    name: school-social-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn school_social_aubrick.wsgi:application --workers=3 --timeout=120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: school_social_aubrick.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        # set in Step 3 to your Vercel URL; keep blank for now
        value: ""
      # If you later use Postgres on Render, add DATABASE_URL here.
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
